//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_TRANS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTORY_TRANS()
        {
            this.TRACE_INV_TRANS = new HashSet<TRACE_INV_TRANS>();
        }
    
        public int ROWID { get; set; }
        public int TRANSACTION_ID { get; set; }
        public string WORKORDER_TYPE { get; set; }
        public string WORKORDER_BASE_ID { get; set; }
        public string WORKORDER_LOT_ID { get; set; }
        public string WORKORDER_SPLIT_ID { get; set; }
        public string WORKORDER_SUB_ID { get; set; }
        public Nullable<short> OPERATION_SEQ_NO { get; set; }
        public Nullable<short> REQ_PIECE_NO { get; set; }
        public string CUST_ORDER_ID { get; set; }
        public Nullable<short> CUST_ORDER_LINE_NO { get; set; }
        public string PURC_ORDER_ID { get; set; }
        public Nullable<short> PURC_ORDER_LINE_NO { get; set; }
        public string PART_ID { get; set; }
        public string TYPE { get; set; }
        public string CLASS { get; set; }
        public decimal QTY { get; set; }
        public decimal COSTED_QTY { get; set; }
        public System.DateTime TRANSACTION_DATE { get; set; }
        public string WAREHOUSE_ID { get; set; }
        public string LOCATION_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string USER_ID { get; set; }
        public string POSTING_CANDIDATE { get; set; }
        public string ADJ_REASON_ID { get; set; }
        public decimal ACT_MATERIAL_COST { get; set; }
        public decimal ACT_LABOR_COST { get; set; }
        public decimal ACT_BURDEN_COST { get; set; }
        public decimal ACT_SERVICE_COST { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<decimal> ADD_BURDEN { get; set; }
        public Nullable<decimal> PIECE_COUNT { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string DIMENSIONS_UM { get; set; }
        public Nullable<int> TRANSFER_TRANS_ID { get; set; }
        public string XFER_IN_TRANSIT { get; set; }
        public string IBT_ID { get; set; }
        public Nullable<short> IBT_LINE_NO { get; set; }
        public string GL_ADJ_ACCT_ID { get; set; }
        public string FROM_WBS_CODE { get; set; }
        public string TO_WBS_CODE { get; set; }
        public string WBS_CODE { get; set; }
        public string DEPARTMENT_ID { get; set; }
        public string COST_CATEGORY_ID { get; set; }
        public Nullable<short> PROJ_REF_SEQ_NO { get; set; }
        public string PROJ_REF_SUB_ID { get; set; }
        public string REVISION_ID { get; set; }
        public string STAGE_ID { get; set; }
        public string ISSUE_REAS_ID { get; set; }
        public string ACT_RATE_ID { get; set; }
        public string ACT_PERIOD_ID { get; set; }
        public string RETRO_RATE_ID { get; set; }
        public string RETRO_PERIOD_ID { get; set; }
        public string RETRO_RATE_CODE { get; set; }
        public Nullable<System.DateTime> LAST_RETRO_DATE { get; set; }
        public int COUNT_SEQUENCE { get; set; }
        public string SITE_ID { get; set; }
        public string USER_DIMENSION_1 { get; set; }
        public string USER_DIMENSION_2 { get; set; }
        public string LOCATION_HOLD_CODE_ID { get; set; }
        public string RET_COST_ZERO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACE_INV_TRANS> TRACE_INV_TRANS { get; set; }
    }
}
