
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_W_GRUPOS
{

    public int ID { get; set; }

    public string NOMBRE { get; set; }

    public string TIPO { get; set; }

}

}
