
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_W_OTROS
{

    public int ID { get; set; }

    public string TIPO { get; set; }

    public string TIPO_SERVICIO { get; set; }

    public string IDCLIENTE { get; set; }

    public string DUI { get; set; }

    public string CANTIDA_MAT_C { get; set; }

    public string CANTIDAD_DUMMIES { get; set; }

    public string ESPECIFICACIONES { get; set; }

    public string ASIGNADA { get; set; }

    public Nullable<int> PASO_ACTUAL { get; set; }

}

}
