//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_QW2_HBI
    {
        public int ID { get; set; }
        public string CODES { get; set; }
        public string PO { get; set; }
        public Nullable<decimal> PRECIO_SV { get; set; }
        public Nullable<decimal> HBI_TIL { get; set; }
        public Nullable<decimal> SAFETY_SCTOCK { get; set; }
        public Nullable<decimal> ON_HAND_CORDER { get; set; }
        public Nullable<decimal> ON_HAND_SMI { get; set; }
        public string QTY { get; set; }
        public Nullable<decimal> PERCENT_SMI { get; set; }
        public Nullable<decimal> QTY_PROCESS { get; set; }
        public Nullable<decimal> QTY_RED { get; set; }
        public string DATE_INV_W { get; set; }
        public string VENDOR_COMENTS { get; set; }
        public string ESTADO { get; set; }
        public string EDIT { get; set; }
        public string PART_ID { get; set; }
        public string REVISION { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<decimal> PRECIO_ORDER { get; set; }
    }
}
