
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_MATERIAL
{

    public int ID { get; set; }

    public string PART_ID { get; set; }

    public string RESINA { get; set; }

    public Nullable<decimal> PORCENTAJE { get; set; }

    public string PROCESO { get; set; }

    public Nullable<int> PIEZA { get; set; }

    public string ESTADO { get; set; }

    public Nullable<int> OPERATION_SEQ { get; set; }

}

}
