//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_W_ADJUNTOS
    {
        public System.Guid Id { get; set; }
        public System.DateTime Creado { get; set; }
        public string Nombre { get; set; }
        public int IdWorkflow { get; set; }
        public string Extension { get; set; }
        public int Descargas { get; set; }
        public string tipo { get; set; }
    }
}
