//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_W_SERVICIOS_PRODUCCION
    {
        public int ID { get; set; }
        public string TIPO { get; set; }
        public string TIPO_REQUERIMIENTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string IDCLIENTE { get; set; }
        public string DUI { get; set; }
        public string FECHA_REQUERIDA { get; set; }
        public string PERSONA_ASIGNADA { get; set; }
        public string TRABAJO_REALIZADO { get; set; }
        public string COMENTARIOS { get; set; }
        public string FECHA_FINALIZACION { get; set; }
        public Nullable<int> PASO_ACTUAL { get; set; }
    }
}
