
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_W_WORKFLOWB2B
{

    public int ID { get; set; }

    public string TIPO { get; set; }

    public string ESTADO { get; set; }

    public string TITULO { get; set; }

    public Nullable<int> PASO_ACTUAL { get; set; }

    public string TIPO_SERVICIO { get; set; }

    public string IDCLIENTE { get; set; }

    public string NOTAS { get; set; }

    public string REFERENCIA_COSTEO { get; set; }

    public string CELULA_TECNICA { get; set; }

    public string NECESITA_MUESTRA { get; set; }

    public string MAT_PRECIO { get; set; }

    public string MAT_CODIGO { get; set; }

    public string MAT_PROVEDOR { get; set; }

    public string MAT_LEADTIME { get; set; }

    public string MAT_DENSIDAD { get; set; }

    public string MAQ_INVERSION { get; set; }

    public string MAQ_LEADTIME { get; set; }

    public string ACC_INVERSION { get; set; }

    public string ACC_LEADTIME { get; set; }

    public string INS_PRECIO { get; set; }

    public string INS_CODIGO { get; set; }

    public string INS_LEADTIME { get; set; }

    public string PAR_PROCESO { get; set; }

    public string PAR_SETUP { get; set; }

    public string PAR_VELOCIDAD { get; set; }

    public string PA_DESPERDICIO_V { get; set; }

    public string PAR_DESPERDICIO_F { get; set; }

    public string UNIDAD_VENTA { get; set; }

    public string MARGEN { get; set; }

    public string LOTE_INDUSTRIAL { get; set; }

    public string DUI { get; set; }

    public string USUARIO { get; set; }

    public string USUARIO_INI { get; set; }

    public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }

    public string INFORMACION_REQ { get; set; }

}

}
