
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_W_FLUJO_ARTES
{

    public int ID { get; set; }

    public string TIPO { get; set; }

    public string ARTE { get; set; }

    public string DUI { get; set; }

    public string RETOQUE { get; set; }

    public string IMPRESION { get; set; }

    public string ASIGNADO { get; set; }

    public Nullable<int> PASO_ACTUAL { get; set; }

    public string NOMBRE_PRODUCTO { get; set; }

    public string USUARIO_INICIADOR { get; set; }

    public string REGION { get; set; }

    public string CLIENTE { get; set; }

}

}
