//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_QW7_SEGUIMIETO_CAMBIOS
    {
        public int ID { get; set; }
        public string FECHA { get; set; }
        public string USUARIO { get; set; }
        public Nullable<decimal> CANTIDAD_SOLICITADA { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA { get; set; }
        public string FECHA_PROMESA { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string CAUSA { get; set; }
        public string PRIORIDAD { get; set; }
        public string PEDIDO { get; set; }
    }
}
