//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_QW7_SEGUIMIETO
    {
        public int ID { get; set; }
        public string NUM_PEDIDO { get; set; }
        public string OT { get; set; }
        public string PART_ID { get; set; }
        public Nullable<decimal> CANTIDAD_SOLICITADA { get; set; }
        public Nullable<decimal> CANTIDAD_ENTREGADA { get; set; }
        public Nullable<decimal> CUMPLIMIENTO { get; set; }
        public string FECHA_PROMESA { get; set; }
        public string FECHA { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public string CAUSA { get; set; }
        public string ESTADO_PEDIDO { get; set; }
        public string LE { get; set; }
        public string FACTURA { get; set; }
        public string PRIORIDAD { get; set; }
        public string FECHA_PED { get; set; }
        public string ESTADO { get; set; }
        public string USUARIO { get; set; }
        public string PO { get; set; }
    }
}
