//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_COMERCIAL
    {
        public int ID { get; set; }
        public string PART_ID { get; set; }
        public string COTIZACION { get; set; }
        public string DUI { get; set; }
        public string ANCHO { get; set; }
        public string LARGO { get; set; }
        public string PESO_TOTAL { get; set; }
        public string PESO_MILLAR { get; set; }
        public string USUARIO { get; set; }
        public string ESTADO { get; set; }
        public string FC_OTROS { get; set; }
        public string UN_X_M2 { get; set; }
        public string UN_X_KG { get; set; }
        public string PESO_X_BOBINA { get; set; }
    }
}
