
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_QW_MH
{

    public int ID { get; set; }

    public string HBI_PART { get; set; }

    public string MH_NUMBER { get; set; }

    public string STATUS { get; set; }

    public Nullable<decimal> WIP { get; set; }

    public string ETA { get; set; }

    public Nullable<decimal> ATDR { get; set; }

    public Nullable<decimal> TRANSITO1 { get; set; }

    public Nullable<decimal> TRANSITO2 { get; set; }

    public Nullable<decimal> TRANSITO3 { get; set; }

    public Nullable<decimal> TRANSITO4 { get; set; }

    public Nullable<decimal> CASE_QTY { get; set; }

    public Nullable<decimal> BOXES { get; set; }

    public string COMMENTS { get; set; }

    public Nullable<int> DAYS { get; set; }

    public string PART_ID { get; set; }

    public string ETIQUETA1 { get; set; }

    public string ETIQUETA2 { get; set; }

    public string ETIQUETA3 { get; set; }

    public string ETIQUETA4 { get; set; }

}

}
