
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_DET_COMERCIAL
{

    public int ID { get; set; }

    public Nullable<int> ID_COMERCIAL { get; set; }

    public string E_REP { get; set; }

    public string E_KG { get; set; }

    public string E_ROLL { get; set; }

    public string C_KG { get; set; }

    public string C_ROLLO { get; set; }

    public string PRECIO_R { get; set; }

    public string PRECIO_2 { get; set; }

    public Nullable<decimal> MC { get; set; }

    public string C_REP { get; set; }

}

}
