//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_QW2_UNDERWEAR
    {
        public int ID { get; set; }
        public string HBI_NUMBER { get; set; }
        public Nullable<decimal> ACTIVE_TILS { get; set; }
        public Nullable<decimal> SUPLIER { get; set; }
        public Nullable<decimal> WIP { get; set; }
        public string PRODUCTION_DATE { get; set; }
        public Nullable<decimal> FGWIP { get; set; }
        public Nullable<decimal> PRICING { get; set; }
        public Nullable<decimal> TRANSITO1 { get; set; }
        public Nullable<decimal> TRANSITO2 { get; set; }
        public Nullable<int> SEMANA { get; set; }
        public Nullable<decimal> UPS { get; set; }
        public Nullable<decimal> CASE_QTY { get; set; }
        public Nullable<decimal> CTNS { get; set; }
        public Nullable<decimal> NRQ { get; set; }
        public Nullable<decimal> MAX_EXPOSURE { get; set; }
        public string COMMENTS { get; set; }
        public string IDENTIFICADOR { get; set; }
        public string ESTADO { get; set; }
        public string PART_ID { get; set; }
        public Nullable<decimal> TRANSITO3 { get; set; }
        public Nullable<decimal> TRANSITO4 { get; set; }
        public string ETIQUETA1 { get; set; }
        public string ETIQUETA2 { get; set; }
        public string ETIQUETA3 { get; set; }
        public string ETIQUETA4 { get; set; }
    }
}
