
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_W_PARAMETROS_PAR
{

    public int ID { get; set; }

    public Nullable<int> IDWORKFLOW { get; set; }

    public string PROCESO { get; set; }

    public string SETUP { get; set; }

    public string VELOCIDAD { get; set; }

    public string PA_DESPERDICIO_V { get; set; }

    public string PAR_DESPERDICIO_F { get; set; }

    public string ESTADO { get; set; }

}

}
