
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_W_WORFLOW_CARTICULO
{

    public int ID { get; set; }

    public string TIPO { get; set; }

    public string TITULO { get; set; }

    public Nullable<int> PASO_ACTUAL { get; set; }

    public Nullable<int> WORKFLOW_ANT { get; set; }

    public string IDCLIENTE { get; set; }

    public string PRODUCTO_EMP { get; set; }

    public string ESTRUCTURA { get; set; }

    public string FORMULA_EXT { get; set; }

    public Nullable<decimal> CANTIDAD_MAX { get; set; }

    public string NUM_PEDIDO { get; set; }

    public string VALIDACION { get; set; }

    public string CARTILLA_CALIDAD { get; set; }

    public string NUM_CARTILLA { get; set; }

    public string TIPO_PEDIDO { get; set; }

    public string NOTAS_PEDIDO { get; set; }

    public string FECHA_ENTREGA { get; set; }

    public string FECHA_VALIDACION_IMP { get; set; }

    public string ESTADO { get; set; }

    public string OBSERVACIONES { get; set; }

    public string FECHA_INICIO { get; set; }

    public Nullable<decimal> TIEMPO_PROCESO { get; set; }

    public Nullable<decimal> TIEMPO_TOTAL { get; set; }

    public string FECHA_FINALIZACION { get; set; }

    public Nullable<int> DIAS_TOTALES { get; set; }

    public string FECHA_ESTIMADA { get; set; }

    public string PROCESO_ACTUAL { get; set; }
        public string DUI { get; set; }

        public string SAR { get; set; }
        public string OC_CANTIDAD_SOLICITADA { get; set; }
        public string TIPO_PROYECTO { get; set; }

        public string COMENTARIOS { get; set; }
    }

}
