//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_QW6_PLANTILLA
    {
        public int ID { get; set; }
        public string PO_NUMBER { get; set; }
        public string CLIENT { get; set; }
        public string CUSTOMER_PART_ID { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string COMENTARIO { get; set; }
        public string PART_ID { get; set; }
        public string ESTADO { get; set; }
        public string ENCABEZADO { get; set; }
        public string MONEDA { get; set; }
        public string USUARIO { get; set; }
        public string BASE { get; set; }
        public string OC { get; set; }
        public string STAGE_ID { get; set; }
    }
}
