
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_BODEGA
{

    public int ID { get; set; }

    public string PART_ID { get; set; }

    public string WORKORDER_BASE_ID { get; set; }

    public string TIPO { get; set; }

    public string WAREHOUSE_ID { get; set; }

    public string LOCATION_ID { get; set; }

    public Nullable<decimal> CANTIDADENVIADA { get; set; }

    public Nullable<decimal> CANTIDADRECIBIDA { get; set; }

    public string DESCRIPCION { get; set; }

    public string USUARIO_ENVIO { get; set; }

    public string USUARIO_RECEPTOR { get; set; }

    public string ESTADO { get; set; }

    public string FECHA { get; set; }

    public Nullable<decimal> CAJAS_ENVIO { get; set; }

    public Nullable<decimal> CAJAS_RECIBO { get; set; }

    public Nullable<decimal> CAJAS_PARCIALES { get; set; }

    public string RECHAZO { get; set; }

    public Nullable<decimal> MILLARES_CAJA { get; set; }

}

}
