//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_PRECIO_SOCK
    {
        public int ID { get; set; }
        public string PART_ID { get; set; }
        public Nullable<decimal> PRECIO1 { get; set; }
        public Nullable<decimal> PRECIO2 { get; set; }
        public Nullable<decimal> PRECIO3 { get; set; }
        public Nullable<decimal> PRECIO4 { get; set; }
        public Nullable<decimal> PRECIO5 { get; set; }
        public Nullable<decimal> PRECIO6 { get; set; }
        public Nullable<decimal> PRECIO7 { get; set; }
        public Nullable<decimal> PRECIO8 { get; set; }
        public Nullable<decimal> PRECIO9 { get; set; }
        public Nullable<decimal> PRECIO10 { get; set; }
    }
}
