//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_COM_PEDIDOS
    {
        public int ID { get; set; }
        public string ESTADO { get; set; }
        public string FECHA_INGRESO { get; set; }
        public string CLIENTE { get; set; }
        public string OC { get; set; }
        public string TIPO { get; set; }
        public string PART_ID { get; set; }
        public string FECHA_ENTREGA { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string REF_COTIZACION { get; set; }
        public string DUI { get; set; }
        public string SEGMENTO { get; set; }
        public string CLUSTER { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string COMMODITY_CODE { get; set; }
        public string UN { get; set; }
        public string FC { get; set; }
        public string IDUSUARIO { get; set; }
        public Nullable<decimal> MARGEN { get; set; }
        public string PEDIDO { get; set; }
        public string TOLERANCIA { get; set; }
        public string CARTILLA { get; set; }
        public string BASE { get; set; }
        public string ORDENCOMPRA { get; set; }
        public string ESTADO_PED { get; set; }
    }
}
