
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TER_QW3_PED_HIST
{

    public int ID { get; set; }

    public string PO_NUMBER { get; set; }

    public Nullable<int> LINEA { get; set; }

    public string ITEM { get; set; }

    public Nullable<decimal> QUANTITY { get; set; }

    public Nullable<decimal> PRECIO_PO { get; set; }

    public Nullable<decimal> PRECIO_OK { get; set; }

    public string VALIDACION { get; set; }

    public Nullable<decimal> ON_HAND { get; set; }

    public Nullable<decimal> CANTIDAD_X_CAJA { get; set; }

    public Nullable<decimal> CAJA_CERRADA { get; set; }

    public Nullable<decimal> DESPACHADO { get; set; }

    public Nullable<decimal> CANTIDAD_ENVIAR { get; set; }

    public string COMENTARIO { get; set; }

    public string ESTADO { get; set; }

    public string PART_ID { get; set; }

    public Nullable<decimal> CAJA_DESPACHAR { get; set; }

    public string CLIENTE { get; set; }

    public string PEDIDO { get; set; }

    public Nullable<int> PED_LINE { get; set; }

    public string FECHA { get; set; }

}

}
