//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_PORC_TEXTIL_HIST
    {
        public int ID { get; set; }
        public string FECHA_MODIFICACION { get; set; }
        public string TIPO { get; set; }
        public string CLIENTE { get; set; }
        public string ARTICULO { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string USUARIO { get; set; }
        public string FECHA_HASTA { get; set; }
        public string FECHA_DESDE { get; set; }
        public Nullable<int> ID_E { get; set; }
    }
}
