

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apiweb.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TERMOAPPEntities : DbContext
{
    public TERMOAPPEntities()
        : base("name=TERMOAPPEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TER_QW3_PRECIO_SMI> TER_QW3_PRECIO_SMI { get; set; }

    public virtual DbSet<TER_QW3_PED> TER_QW3_PED { get; set; }

    public virtual DbSet<TER_QW3_PRECIO_MH> TER_QW3_PRECIO_MH { get; set; }

    public virtual DbSet<TER_QW2_HBI> TER_QW2_HBI { get; set; }

    public virtual DbSet<TER_QW3_PED_HIST> TER_QW3_PED_HIST { get; set; }

    public virtual DbSet<TER_QW6_PLANTILLA> TER_QW6_PLANTILLA { get; set; }

    public virtual DbSet<TER_QW7_SEGUIMIETO_CAMBIOS> TER_QW7_SEGUIMIETO_CAMBIOS { get; set; }

    public virtual DbSet<TER_QW6_PLANTILLA_PED> TER_QW6_PLANTILLA_PED { get; set; }

    public virtual DbSet<TER_PRECIO_SOCK> TER_PRECIO_SOCK { get; set; }

    public virtual DbSet<TER_QW_MH> TER_QW_MH { get; set; }

    public virtual DbSet<TER_QW7_SEGUIMIETO> TER_QW7_SEGUIMIETO { get; set; }

    public virtual DbSet<TER_QW2_UNDERWEAR> TER_QW2_UNDERWEAR { get; set; }

    public virtual DbSet<TER_BODEGA> TER_BODEGA { get; set; }

    public virtual DbSet<TER_W_FLUJO_ARTES> TER_W_FLUJO_ARTES { get; set; }

    public virtual DbSet<TER_W_GRUPOS> TER_W_GRUPOS { get; set; }

    public virtual DbSet<TER_W_SLA> TER_W_SLA { get; set; }

    public virtual DbSet<TER_W_PARAMETROS_ACC> TER_W_PARAMETROS_ACC { get; set; }

    public virtual DbSet<TER_W_PARAMETROS_MAQ> TER_W_PARAMETROS_MAQ { get; set; }

    public virtual DbSet<TER_W_PARAMETROS_PAR> TER_W_PARAMETROS_PAR { get; set; }

    public virtual DbSet<TER_W_ADJUNTOS> TER_W_ADJUNTOS { get; set; }

    public virtual DbSet<TER_W_PARAMETROS_INS> TER_W_PARAMETROS_INS { get; set; }

    public virtual DbSet<TER_W_PARAMETROS_MAT> TER_W_PARAMETROS_MAT { get; set; }

    public virtual DbSet<TER_W_SERVICIOS_PRODUCCION> TER_W_SERVICIOS_PRODUCCION { get; set; }

    public virtual DbSet<TER_W_WORKFLOWB2B> TER_W_WORKFLOWB2B { get; set; }

    public virtual DbSet<TER_W_OTROS> TER_W_OTROS { get; set; }

    public virtual DbSet<TER_W_WORKFLOW_MUESTRA> TER_W_WORKFLOW_MUESTRA { get; set; }

    public virtual DbSet<TER_W_WORFLOW_CARTICULO> TER_W_WORFLOW_CARTICULO { get; set; }

    public virtual DbSet<TER_COMERCIAL> TER_COMERCIAL { get; set; }

    public virtual DbSet<TER_W_CORREOS> TER_W_CORREOS { get; set; }

}

}

