//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRACE()
        {
            this.TRACE_INV_TRANS = new HashSet<TRACE_INV_TRANS>();
        }
    
        public int ROWID { get; set; }
        public string PART_ID { get; set; }
        public string ID { get; set; }
        public string NUMBERING_ID { get; set; }
        public decimal OUT_QTY { get; set; }
        public decimal IN_QTY { get; set; }
        public decimal REPORTED_QTY { get; set; }
        public decimal ASSIGNED_QTY { get; set; }
        public string APROPERTY_1 { get; set; }
        public string APROPERTY_2 { get; set; }
        public string APROPERTY_3 { get; set; }
        public string APROPERTY_4 { get; set; }
        public string APROPERTY_5 { get; set; }
        public Nullable<decimal> NPROPERTY_1 { get; set; }
        public Nullable<decimal> NPROPERTY_2 { get; set; }
        public Nullable<decimal> NPROPERTY_3 { get; set; }
        public Nullable<decimal> NPROPERTY_4 { get; set; }
        public Nullable<decimal> NPROPERTY_5 { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public decimal DISP_IN_QTY { get; set; }
        public decimal DISP_OUT_QTY { get; set; }
        public decimal UNAVAILABLE_QTY { get; set; }
        public string OWNER_ID { get; set; }
        public string LOT_ID { get; set; }
        public string SERIAL_ID { get; set; }
        public Nullable<decimal> COMMITTED_QTY { get; set; }
        public Nullable<System.DateTime> PRODUCTION_DATE { get; set; }
        public Nullable<System.DateTime> RECEIVE_BY_DATE { get; set; }
        public Nullable<System.DateTime> AVAILABLE_DATE { get; set; }
        public Nullable<System.DateTime> SHIP_BY_DATE { get; set; }
        public string SITE_ID { get; set; }
    
        public virtual PART PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACE_INV_TRANS> TRACE_INV_TRANS { get; set; }
    }
}
