//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apiweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRACE_INV_TRANS
    {
        public int ROWID { get; set; }
        public string PART_ID { get; set; }
        public string TRACE_ID { get; set; }
        public int TRANSACTION_ID { get; set; }
        public decimal QTY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public decimal COSTED_QTY { get; set; }
    
        public virtual INVENTORY_TRANS INVENTORY_TRANS { get; set; }
        public virtual TRACE TRACE { get; set; }
    }
}
